# Generated by Django 3.1.6 on 2021-02-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20210219_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pagesNum',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
